spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev
  application: 
    name: microservicecloud-config-xn-dev
---
spring: 
  profiles: test
  application: 
    name: microservicecloud-config-xn-test
#保存为utf-8